class Cidade {
  String nome;

  Cidade(this.nome);
}

class CidadeDados {
  static List<Cidade> getCidades() {
    List<Cidade> lista = [];
    lista.add(Cidade('Abadia de Goiás'));
    lista.add(Cidade('Abadiânia'));
    lista.add(Cidade('Acreúna'));
    lista.add(Cidade('Adelândia'));
    lista.add(Cidade('Água Fria de Goiás'));
    lista.add(Cidade('Água Limpa'));
    lista.add(Cidade('Águas Lindas de Goiás'));
    lista.add(Cidade('Alexânia'));
    lista.add(Cidade('Aloândia'));
    lista.add(Cidade('Alto Horizonte'));
    lista.add(Cidade('Alto Paraíso de Goiás'));
    lista.add(Cidade('Alvorada do Norte'));
    lista.add(Cidade('Amaralina'));
    lista.add(Cidade('Americano do Brasil'));
    lista.add(Cidade('Amorinópolis'));
    lista.add(Cidade('Anápolis'));
    lista.add(Cidade('Anhanguera'));
    lista.add(Cidade('Anicuns'));
    lista.add(Cidade('Aparecida de Goiânia'));
    lista.add(Cidade('Aparecida do Rio Doce'));
    lista.add(Cidade('Aporé'));
    lista.add(Cidade('Araçu'));
    lista.add(Cidade('Aragarças'));
    lista.add(Cidade('Aragoiânia'));
    lista.add(Cidade('Araguapaz'));
    lista.add(Cidade('Arenópolis'));
    lista.add(Cidade('Aruanã'));
    lista.add(Cidade('Aurilândia'));
    lista.add(Cidade('Avelinópolis'));
    lista.add(Cidade('Baliza'));
    lista.add(Cidade('Barro Alto'));
    lista.add(Cidade('Bela Vista de Goiás'));
    lista.add(Cidade('Bom Jardim de Goiás'));
    lista.add(Cidade('Bom Jesus de Goiás'));
    lista.add(Cidade('Bonfinópolis'));
    lista.add(Cidade('Bonópolis'));
    lista.add(Cidade('Brazabrantes'));
    lista.add(Cidade('Britânia'));
    lista.add(Cidade('Buriti Alegre'));
    lista.add(Cidade('Buriti de Goiás'));
    lista.add(Cidade('Buritinópolis'));
    lista.add(Cidade('Cabeceiras'));
    lista.add(Cidade('Cachoeira Alta'));
    lista.add(Cidade('Cacheira de Goiás'));
    lista.add(Cidade('Cachoeira Dourada'));
    lista.add(Cidade('Caçu'));
    lista.add(Cidade('Caiapônia'));
    lista.add(Cidade('Caldas Novas'));
    lista.add(Cidade('Caldazinha'));
    lista.add(Cidade('Campestre de Goiás'));
    lista.add(Cidade('Campinaçu'));
    lista.add(Cidade('Campinorte'));
    lista.add(Cidade('Campo Alegre de Goiás'));
    lista.add(Cidade('Campo Limpo de Goiás'));
    lista.add(Cidade('Campos Belos'));
    lista.add(Cidade('Campos Verdes'));
    lista.add(Cidade('Carmo do Rio Verde'));
    lista.add(Cidade('Castelândia'));
    lista.add(Cidade('Catalão'));
    lista.add(Cidade('Caturaí'));
    lista.add(Cidade('Cavalcante'));
    lista.add(Cidade('Ceres'));
    lista.add(Cidade('Cezarina'));
    lista.add(Cidade('Chapadão do Céu'));
    lista.add(Cidade('Cidade Ocidental'));
    lista.add(Cidade('Cocalzinho de Goiás'));
    lista.add(Cidade('Colinas do Sul'));
    lista.add(Cidade('Córrego do Ouro'));
    lista.add(Cidade('Corumbá de Goiás'));
    lista.add(Cidade('Corumbaíba'));
    lista.add(Cidade('Cristalina'));
    lista.add(Cidade('Cristianópolis'));
    lista.add(Cidade('Crixás'));
    lista.add(Cidade('Cromínia'));
    lista.add(Cidade('Cumari'));
    lista.add(Cidade('Damianópolis'));
    lista.add(Cidade('Damolândia'));
    lista.add(Cidade('Davinópolis'));
    lista.add(Cidade('Diorama'));
    lista.add(Cidade('Divinópolis de Goiás'));
    lista.add(Cidade('Doverlândia'));
    lista.add(Cidade('Edealina'));
    lista.add(Cidade('Edéia'));
    lista.add(Cidade('Estrela do Norte'));
    lista.add(Cidade('Faina'));
    lista.add(Cidade('Fazenda Nova'));
    lista.add(Cidade('Firminópolis'));
    lista.add(Cidade('Flores de Goiás'));
    lista.add(Cidade('Formosa'));
    lista.add(Cidade('Formoso'));
    lista.add(Cidade('Gameleira de Goiás'));
    lista.add(Cidade('Goianápolis'));
    lista.add(Cidade('Goiandira'));
    lista.add(Cidade('Goianésia'));
    lista.add(Cidade('Goiânia'));
    lista.add(Cidade('Goianira'));
    lista.add(Cidade('Goiás'));
    lista.add(Cidade('Goiatuba'));
    lista.add(Cidade('Gouvelândia'));
    lista.add(Cidade('Guapó'));
    lista.add(Cidade('Guaraíta'));
    lista.add(Cidade('Guarani de Goiás'));
    lista.add(Cidade('Guarinos'));
    lista.add(Cidade('Heitoraí'));
    lista.add(Cidade('Hidrolândia'));
    lista.add(Cidade('Hidrolina'));
    lista.add(Cidade('Iaciara'));
    lista.add(Cidade('Inaciolândia'));
    lista.add(Cidade('Indiara'));
    lista.add(Cidade('Inhumas'));
    lista.add(Cidade('Ipameri'));
    lista.add(Cidade('Ipiranga de Goiás'));
    lista.add(Cidade('Iporá'));
    lista.add(Cidade('Israelândia'));
    lista.add(Cidade('Itaberaí'));
    lista.add(Cidade('Itaguari'));
    lista.add(Cidade('Itaguaru'));
    lista.add(Cidade('Itajá'));
    lista.add(Cidade('Itapaci'));
    lista.add(Cidade('Itapirapuã'));
    lista.add(Cidade('Itapuranga'));
    lista.add(Cidade('Itarumã'));
    lista.add(Cidade('Itauçu'));
    lista.add(Cidade('Itumbiara'));
    lista.add(Cidade('Ivolândia'));
    lista.add(Cidade('Jandaia'));
    lista.add(Cidade('Jaraguá'));
    lista.add(Cidade('Jataí'));
    lista.add(Cidade('Jaupaci'));
    lista.add(Cidade('Jesúpolis'));
    lista.add(Cidade('Joviânia'));
    lista.add(Cidade('Jussara'));
    lista.add(Cidade('Lagoa Santa'));
    lista.add(Cidade('Leopoldo de Bulhões'));
    lista.add(Cidade('Luziânia'));
    lista.add(Cidade('Mairipotaba'));
    lista.add(Cidade('Mambaí'));
    lista.add(Cidade('Mara Rosa'));
    lista.add(Cidade('Marzagão'));
    lista.add(Cidade('Matrinchã'));
    lista.add(Cidade('Maurilândia'));
    lista.add(Cidade('Mimoso de Goiás'));
    lista.add(Cidade('Minaçu'));
    lista.add(Cidade('Mineiros'));
    lista.add(Cidade('Moiporá'));
    lista.add(Cidade('Monte Alegre de Goiás'));
    lista.add(Cidade('Montes Claros de Goiás'));
    lista.add(Cidade('Montividiu'));
    lista.add(Cidade('Montividiu do Norte'));
    lista.add(Cidade('Morrinhos'));
    lista.add(Cidade('Morro Agudo de Goiás'));
    lista.add(Cidade('Mossâmedes'));
    lista.add(Cidade('Mozarlândia'));
    lista.add(Cidade('Mundo Novo'));
    lista.add(Cidade('Mutunópolis'));
    lista.add(Cidade('Nazário'));
    lista.add(Cidade('Nerópolis'));
    lista.add(Cidade('Niquelândia'));
    lista.add(Cidade('Nova América'));
    lista.add(Cidade('Nova Aurora'));
    lista.add(Cidade('Nova Crixás'));
    lista.add(Cidade('Nova Glória'));
    lista.add(Cidade('Nova Iguaçu de Goiás'));
    lista.add(Cidade('Nova Roma'));
    lista.add(Cidade('Nova Veneza'));
    lista.add(Cidade('Novo Brasil'));
    lista.add(Cidade('Novo Gama'));
    lista.add(Cidade('Novo Planalto'));
    lista.add(Cidade('Orizona'));
    lista.add(Cidade('Ouro Verde de Goiás'));
    lista.add(Cidade('Ouvidor'));
    lista.add(Cidade('Padre Bernardo'));
    lista.add(Cidade('Palestina de Goiás'));
    lista.add(Cidade('Palmeiras de Goiás'));
    lista.add(Cidade('Palmelo'));
    lista.add(Cidade('Palminópolis'));
    lista.add(Cidade('Panamá'));
    lista.add(Cidade('Paranaiguara'));
    lista.add(Cidade('Paraúna'));
    lista.add(Cidade('Perolândia'));
    lista.add(Cidade('Petrolina de Goiás'));
    lista.add(Cidade('Pilar de Goiás'));
    lista.add(Cidade('Piracanjuba'));
    lista.add(Cidade('Piranhas'));
    lista.add(Cidade('Pirenópolis'));
    lista.add(Cidade('Pires do Rio'));
    lista.add(Cidade('Planaltina'));
    lista.add(Cidade('Pontalina'));
    lista.add(Cidade('Porangatu'));
    lista.add(Cidade('Porteirão'));
    lista.add(Cidade('Portelândia'));
    lista.add(Cidade('Posse'));
    lista.add(Cidade('Professor Jamil'));
    lista.add(Cidade('Quirinópolis'));
    lista.add(Cidade('Rialma'));
    lista.add(Cidade('Rianápolis'));
    lista.add(Cidade('Rio Quente'));
    lista.add(Cidade('Rio Verde'));
    lista.add(Cidade('Rubiataba'));
    lista.add(Cidade('Sanclerlândia'));
    lista.add(Cidade('Santa Bárbara de Goiás'));
    lista.add(Cidade('Santa Cruz de Goiás'));
    lista.add(Cidade('Santa Fé de Goiás'));
    lista.add(Cidade('Santa Helena de Goiás'));
    lista.add(Cidade('Santa Isabel'));
    lista.add(Cidade('Santa Rita do Araguaia'));
    lista.add(Cidade('Santa Rita do Novo Destino'));
    lista.add(Cidade('Santa Rosa de Goiás'));
    lista.add(Cidade('Santa Tereza de Goiás'));
    lista.add(Cidade('Santa Terezinha de Goiás'));
    lista.add(Cidade('Santo Antônio da Barra'));
    lista.add(Cidade('Santo Antônio de Goiás'));
    lista.add(Cidade('Santo Antônio do Descoberto'));
    lista.add(Cidade('São Domingos'));
    lista.add(Cidade('São Francisco de Goiás'));
    lista.add(Cidade('São João da Paraúna'));
    lista.add(Cidade('São João d\'Aliança'));
    lista.add(Cidade('São Luís de Montes Belos'));
    lista.add(Cidade('São Luiz do Norte'));
    lista.add(Cidade('São Miguel do Araguaia'));
    lista.add(Cidade('São Miguel do Passa Quatro'));
    lista.add(Cidade('São Patrício'));
    lista.add(Cidade('São Simão'));
    lista.add(Cidade('Senador Canedo'));
    lista.add(Cidade('Serranópolis'));
    lista.add(Cidade('Silvânia'));
    lista.add(Cidade('Simolândia'));
    lista.add(Cidade('Sítio d\'Abadia'));
    lista.add(Cidade('Taquaral de Goiás'));
    lista.add(Cidade('Teresina de Goiás'));
    lista.add(Cidade('Terezópolis de Goiás'));
    lista.add(Cidade('Três Ranchos'));
    lista.add(Cidade('Trindade'));
    lista.add(Cidade('Trombas'));
    lista.add(Cidade('Turvânia'));
    lista.add(Cidade('Turvelândia'));
    lista.add(Cidade('Uirapuru'));
    lista.add(Cidade('Uruaçu'));
    lista.add(Cidade('Uruana'));
    lista.add(Cidade('Urutaí'));
    lista.add(Cidade('Valparaíso de Goiás'));
    lista.add(Cidade('Varjão'));
    lista.add(Cidade('Vianópolis'));
    lista.add(Cidade('Vicentinópolis'));
    lista.add(Cidade('Vila Boa'));
    lista.add(Cidade('Vila Propício'));
    return lista;
  }
}
